Bootstrap: debootstrap

OSVersion: stretch

MirrorURL:  http://ftp.us.debian.org/debian/

%help
    Contains necessary packages and libraries to build and run FastSim (https://github.com/vrastil/FastSim).

%post
    apt-get -y update
    apt-get -y install build-essential
    apt-get -y install gcc-6 g++-6 libstdc++6 python python-pip
    apt-get -y install cmake git swig wget vim valgrind
    apt-get -y install libgsl-dev libfftw3-dev pkg-config
    apt-get -y install libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-system-dev
    pip install numpy

    # get all libraries
    mkdir /data && cd /data
    git clone https://github.com/LSSTDESC/CCL.git
    git clone https://github.com/vrastil/FastSim.git

    #######
    # CCL #
    #######
    cd CCL
    git checkout
    mkdir build && cd build
    cmake ..
    make
    make install
    cd ../..

    ########
    # JSON #
    ########
    wget https://github.com/nlohmann/json/releases/download/v3.2.0/json.hpp
    mv json.hpp /usr/local/include

    ###########
    # FastSim #
    ###########
    cd FastSim
    make
    make install
    cd ..

    ############
    # Clean-up #
    ############
    ldconfig
    rm -rf *
    apt-get clean
